### ISSUE TITLE
Not compile with Clang 15: call to undeclared function 'meta_keybindings_set_custom_handler'; ISO C99 and later do not support implicit function declarations

### ISSUE THREAD

**Issue by AngryPenguinPL** [BuddiesOfBudgie/budgie-desktop#194]
## Description

When trying compile Budgie desktop with Clang 15 I see build error. Worth to add compilation with GCC 12.2.0 works fine.
```
src/wm/budgie-wm.p/wm.c:5466:2: error: call to undeclared function 'meta_keybindings_set_custom_handler'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
DEBUG util.py:446:          meta_keybindings_set_custom_handler ("panel-main-menu", _budgie_budgie_wm_launch_menu_meta_key_handler_func, g_object_ref (self), g_object_unref);
DEBUG util.py:446:          ^
DEBUG util.py:446:  1 error generated.
```

Full build log: https://file-store.openmandriva.org/api/v1/file_stores/07eba8a2fe7bc3ef9cf30c8fb549922f527da555.log?show=true

## Budgie version

Budgie 10.6.4

## Operating system

OpenMandriva Cooker

## Steps to reproduce the issue

1. Install LLVM/Clang 15
2. Compile Budgie desktop 10.6.4
3. See build error

## Actual result

Compilation error

## Expected result
Package compile fine with Clang 15

**Comment by fossfreedom** [comment]
Hmm ... clang 15 doesn't have full c11 compatibility that this project requires

https://clang.llvm.org/c_status.html

**Comment by serebit** [comment]
I tried compiling both master and v10.6.4 with clang 15 (using a Debian Sid docker image), and while I saw a couple compiler warnings about the linker arguments used, I didn't get this particular warning. I'll have to try OpenMandriva.

**Comment by serebit** [comment]
Tried in an OpenMandriva Cooker container, building directly from the [spec](https://github.com/OpenMandrivaAssociation/budgie-desktop/blob/master/budgie-desktop.spec), and it produced the same compiler output as Debian. Confirmed via Meson output that it was using clang 15.0.6 for the build, too. Unless I'm missing something, it seems to work fine - maybe one of the clang point releases fixed it.

**Comment by AngryPenguinPL** [comment]
Hi,
Yes, looks like this issue is fixed by new Clang point release.

Until then, we had to use a workaround in the form of an add -Wno-implicit-function-declaration to the compiler.

By this commit: https://github.com/OpenMandrivaAssociation/budgie-desktop/commit/a6acef5cfa014e21a66eff2a590b49bb6fe7943f

This allow to compile on clang 15.0.0.

as far as I know -- implicit-function-declaration with Clang 15.0 was changed from a warning to an error.
Here: https://releases.llvm.org/15.0.0/tools/clang/docs/ReleaseNotes.html#improvements-to-clang-s-diagnostics
>The -Wimplicit-function-declaration warning diagnostic now defaults to an error in C99 and later. Prior to C2x, it may be downgraded to a warning with -Wno-error=implicit-function-declaration, or disabled entirely with -Wno-implicit-function-declaration. As of C2x, support for implicit function declarations has been removed, and the warning options will have no effect.

No idea, why it was reverted in new Clang point releases.

Anyway here is bug topic agains GCC:  https://gcc.gnu.org/bugzilla/show_bug.cgi?id=91092

**Comment by serebit** [comment]
I suppose it's also possible that a newer version of Mutter fixed this.

**Comment by serebit** [comment]
Either way, this seems to be resolved, so I'll mark it as third-party/wontfix. If it comes up again, feel free to reopen the issue.

**Comment by kostadinsh** [comment]
I can reproduce this with Budgie 10.8.2 and GCC 14

```
src/wm/budgie-wm.p/wm.c:7072:9: error: implicit declaration of function ‘meta_keybindings_set_custom_handler’ [-Wimplicit-function-declaration]
 7072 |         meta_keybindings_set_custom_handler ("panel-main-menu", _budgie_budgie_wm_launch_menu_meta_key_handler_func, g_object_ref (self), g_object_unref);
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

[complete build log](https://github.com/BuddiesOfBudgie/budgie-desktop/files/13871520/build.log)

**Comment by JoshStrobl** [comment]
Can confirm, valid issue with gcc 14.
